name: Build Release for Google Play and RuStore

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11.9'

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Buildozer global directory
      uses: actions/cache@v5
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libffi-dev \
          libssl-dev \
          libgmp3-dev \
          zlib1g-dev \
          unzip \
          zip \
          tar \
          autoconf \
          automake \
          libtool \
          pkg-config \
          cmake \
          patch
        python -m pip install --upgrade pip
        pip install "pip<24.1"
        pip install cython==0.29.33 buildozer

    # 1. Восстанавливаем оригинальный постоянный ключ из созданных секретов
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

    # 2. Собираем подписанный релиз
    - name: Build Release with Buildozer
      env:
        APP_ANDROID_KEYSTORE: release.keystore
        APP_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        APP_ANDROID_KEYALIAS: orthodox_alias
        APP_ANDROID_KEYALIAS_PASSWORD: ${{ secrets.KEYALIAS_PASSWORD }}
      run: |
        mkdir -p ~/.buildozer
        buildozer android release

    # 3. Загружаем скомпилированные пакеты (AAB для Google Play) в Артефакты
    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Orthodox-Calendar-GooglePlay-AAB
        path: |
          bin/*.aab
          .buildozer/android/platform/build-*/dists/*/build/outputs/bundle/release/*.aab
        retention-days: 14

    # 4. Загружаем скомпилированные пакеты (APK для RuStore) в Артефакты
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Orthodox-Calendar-RuStore-APK
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/build/outputs/apk/release/*.apk
        retention-days: 14
